"""add column for messages tables

Revision ID: 3bd5bd3fa2b6
Revises: 89bccb71773c
Create Date: 2023-11-26 03:08:32.121920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd5bd3fa2b6'
down_revision = '89bccb71773c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_checked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('is_checked')

    # ### end Alembic commands ###
